In [ ]:
# How to create a random list
# How to set a random seed
# How to generate a random dictionary
# How to generate a random numpy array
# How to generate a random number, string
# When to use

In [2]:
import random
random.__all__

['Random',
 'SystemRandom',
 'betavariate',
 'binomialvariate',
 'choice',
 'choices',
 'expovariate',
 'gammavariate',
 'gauss',
 'getrandbits',
 'getstate',
 'lognormvariate',
 'normalvariate',
 'paretovariate',
 'randbytes',
 'randint',
 'random',
 'randrange',
 'sample',
 'seed',
 'setstate',
 'shuffle',
 'triangular',
 'uniform',
 'vonmisesvariate',
 'weibullvariate']

In [8]:
# # How to set a random seed
random.seed(10)

In [11]:
# How to create a random float
a1 = random.random()
print(a1)
type(a1)

0.5780913011344704


float

In [40]:
# single Random integer between(including) the numbers
random.randint(5,10)

6

In [51]:
# Picking randomly a number
a = [1,2,3,4,5]
random.choice(a)

4

In [66]:
# Random Strings
random.sample(['red', 'blue'], counts=[4, 2], k=6)  # red is always 4, blue is 2 but the order is random

['red', 'blue', 'red', 'blue', 'red', 'red']

In [75]:
random.sample([1,3], counts=[4, 2], k=6) 

[1, 1, 1, 3, 3, 1]

In [67]:
# Random numbers
random.sample(range(1,101),k=5)

[100, 99, 13, 57, 22]

In [71]:
import numpy as np
np.random.randint(1,101,size=5)

array([29, 55, 63, 78, 66])

In [76]:
# range is built in and arange is from numpy
np.arange(1,6,2) # 1 to 6 in step of 2

array([1, 3, 5])

In [79]:
np.array(range(1,6,2)) # np.arange(1,6,2)

array([1, 3, 5])